FROM node:12

ENV PORT 3000

# Create app directory
RUN mkdir -p /usr/src/app/client
WORKDIR /usr/src/app/client

# Installing dependencies
COPY package*.json /usr/src/app/client/
RUN npm install

# Copying source files
COPY . /usr/src/app/client/

# Building app
RUN npm run build
EXPOSE 3000

# Running the app
CMD "npm" "run" "dev"