version: "2.4"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  koa:
    ports:
      - 4000:4000
    build:
      context: server
    volumes:
      - ./server:/usr/src/app/server
    depends_on:
      - postgres
    environment:
      - NODE_ENV=docker

  nextjs:
    ports:
      - 3000:3000
    build:
      context: client
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
      - /usr/src/app/client/.next
