FROM node:14

ENV PORT 4000

# Create app directory
RUN mkdir -p /usr/src/app/server
WORKDIR /usr/src/app/server

# Installing dependencies
COPY package*.json /usr/src/app/server/
RUN npm install

# Copying source files
COPY . /usr/src/app/server/

EXPOSE 4000

# Running the app
CMD "npm" "run" "dev"